name: ğŸ“¦ Script Feed-RSS

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: âš™ï¸ Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: âš™ï¸ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir

    - name: âœ… Run Script
      run: |
        python ./src/script.py

    - name: âš™ï¸ Git Config
      run: |
        git config --global user.email "github@fernandocelmer.com"
        git config --global user.name "Auto Commit"

    - name: ğŸ“ Git Process 
      run: |
        git checkout develop
        git add src/assets/rss-sema-rs.xml
        git commit -a -m "âš™ï¸ FEATURE - Update XML"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # continue-on-error: true
